version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:12.7
    networks:
      - my-nw
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: sample
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  my-nw:
